export const modelAssetFiles = [
  "appAssets.ts",
  "blockDefinition.ts",
  "compiler.ts",
  "compilerContext.ts",
  "connection.ts",
  "cppBlockCatalog.ts",
  "cppBuilder.ts",
  "diagram.ts",
  "diagramBlock.ts",
  "endpoint.ts",
  "index.ts",
  "library.ts",
  "palette.ts",
] as const;
