import {ExecutionContext} from "./context";
import {push} from "./push";
import {gpio} from "./gpio";
import ScopeF64 = push.ScopeF64;
import ProductF64 = push.ProductF64;
import ConstantF64 = push.ConstantF64;
import GpioInF64 = gpio.push.GpioInF64;
import CosF64 = push.CosF64;
import RampF64 = push.RampF64;

/**
 * An example diagram that can be generated by the IDE
 * @author Pedro Bolúdes
 * @title Diagram 1
 * @param ec Execution context
 */
export function diagram(ec: ExecutionContext): void {
  /**
   * @title Scope 1
   * @x 10
   * @y 40
   */
  const scope_0 = new ScopeF64(0, new Uint8Array([3]), ec, 60, 10);

  const [
    [
      /**
       * @title custom_user_title_1
       */
      scope_0_out_0,

      /**
       * @title scope_0_out_1
       */
      scope_0_out_1,

      /**
       * @title scope_0_out_2
       */
      scope_0_out_2
    ]
  ] = scope_0.apply();

  /**
   * @title Product 1
   * @x 100
   * @y 40
   */
  const product_0 = new ProductF64(1, new Uint8Array([2]), ec, new Float64Array([1, 1]));

  const [
    [
      product_0_out_0,
      product_0_out_1
    ]
  ] = product_0.apply([
    /**
     * @connection product_0_out_0__scope_0_out_0
     */
    scope_0_out_0
  ]);

  /**
   * @title Constant 1
   * @x 190
   * @y 68
   */
  const constant_0 = new ConstantF64(2, new Uint8Array([1]), ec, 10, 1);

  constant_0.apply([
    /**
     * @title An input title
     * @connection product_0_out_0__constant_0[0]
     */
    product_0_out_0
  ]);

  /**
   * @title GpioIn 1
   * @x 190
   * @y 170
   */
  const gpio_in_0 = new GpioInF64(3, new Uint8Array([1]), ec, new Uint8Array([0]));

  gpio_in_0.apply([
    [
      /**
       * @connection product_0_out_1__gpio_in_0_in[0][0]
       */
      product_0_out_1,

      /**
       * @title connection title
       */
      scope_0_out_1
    ]
  ]);

  /**
   * @title Cos 1
   * @x 100
   * @y 300
   */
  const cos_0 = new CosF64(4, new Uint8Array([1]), ec);

  const [
    /**
     * @title cos_0_out_0
     */
    cos_0_out_0
  ] = cos_0.apply([
    /**
     * @connection scope_0_out_2__cos_0[0]
     */
    scope_0_out_2
  ]);

  /**
   * @title Ramp 1
   * @x 190
   * @y 300
   */
  const ramp_0 = new RampF64(5, new Uint8Array([1]), ec, 10);

  ramp_0.apply([
    /**
     * @connection cos_0_out_0__ramp_0[0]
     */
    cos_0_out_0
  ])
}